### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by dariocast** [eu-digital-identity-wallet/eudi-srv-pid-issuer#189]
Just to ask if you can release a Dockerfile to build the image of the service

**Comment by dariocast** [comment]
Hi, thanks for your clarification. By the way I was referring to a way to build a docker image of the project after making some changes to the codebase in a personal fork.

**Comment by babisRoutis** [comment]
> Hi, thanks for your clarification. By the way I was referring to a way to build a docker image of the project after making some changes to the codebase in a personal fork.

Good morning @dariocast 

Building locally the docker image is rather straightforward. 

Issue the command

```ssh
./gradlew bootBuildImage
```

This would create `docker.io/build/pid-issuer:latest` 

Please let me know if this answers your issue.

PS: Project uses springboot gradle plugin for creating the docker image. Should you need to customize this, you could check [here](https://docs.spring.io/spring-boot/gradle-plugin/packaging-oci-image.html)

**Comment by dariocast** [comment]
Thank you again, I will check your instruction as soon as possible
