### ISSUE TITLE
Possible bug during SD-JWT VC creation

### ISSUE THREAD

**Issue by charsleysa** [eu-digital-identity-wallet/eudi-srv-pid-issuer#227]
I believe this line is incorrect
https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer/blob/main/src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt#L148
`pid.ageBirthYear?.let { sd(Attributes.AgeInYears.name, it.value) }`

I believe it should use `pid.ageInYears` instead of `pid.ageBirthYear`

**Comment by dzarras** [comment]
Hi @charsleysa,

Thanks for reporting this. A fix has been merged in `main`.

Kind regards.
